// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemon_Web_App.Data;

namespace Pokemon_Web_App.Migrations
{
    [DbContext(typeof(PokemonAppContext))]
    [Migration("20190609100625_CreatePokemons")]
    partial class CreatePokemons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokemon_Web_App.Models.Account", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<Guid>("TeamID");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("AccountTable");
                });

            modelBuilder.Entity("Pokemon_Web_App.Models.Pokemon", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abilities");

                    b.Property<string>("Category");

                    b.Property<string>("Gender");

                    b.Property<float>("Height");

                    b.Property<string>("ImageLocation");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<float>("Weight");

                    b.HasKey("ID");

                    b.ToTable("PokemonTable");
                });

            modelBuilder.Entity("Pokemon_Web_App.Models.Team", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.Property<string>("description");

                    b.HasKey("ID");

                    b.ToTable("TeamTable");
                });
#pragma warning restore 612, 618
        }
    }
}
